### PR TITLE
Add protocol fields to Service and Ingress info items

### PR DESCRIPTION
**Pull request by barney-s**
For #131

### CODE REVIEW

**Comment by barney-s** [comment]
Please review @nan-yu @huyhg

**Comment by barney-s** [comment]
@mortent please review

**Comment by huyhg** [comment]
LGTM

**Comment by mortent** [comment]
I don't see any big issues with this change, but could you explain why we are adding this? Either in the PR or in the issue.

**Comment by barney-s** [comment]
It was a request from an user of application CR #95 

Add support for protocol string in the service and ingress info sections.
This helps with users of application crd to construct URL with appropriate protocol.

https://EXTERNAL-IP
or
http://EXTERNAL-IP

**Pull request merged**
