### PR TITLE
Fixed typo in README.md

### PR DESCRIPTION
**Pull request by jonparker**
Fixed typo

### CODE REVIEW

**Comment by mattfarina** [comment]
@jonparker could you please sign the CNCF CLA. All contributions need to be from someone with a signed CLA. The comment at https://github.com/kubernetes-sigs/application/pull/96#issuecomment-466637926 has details on signing it.

**Comment by jonparker** [comment]
Sorry I am trying to get the email from HelloSign but it hasn't come through.

**Pull request closed without merging**
