### PR TITLE
Give support of ppc64le

### PR DESCRIPTION
**Pull request by zheddie**
Here's a support of ppc64le. Please help to review and commit. thanks.
/cc @jinchihe, @hougangliu

### CODE REVIEW

**Comment by zheddie** [comment]
I guess I have signed the CLA. Please help to check. thanks.

**Comment by zheddie** [comment]
Anybody here can do a help on it? I am sure I have signed the CLA, and give a correct email address, which is same as what I used  to do the PR. But the Robot still block me as of the CLA.  :-(

**Comment by barney-s** [comment]
LGTM

**Comment by zheddie** [comment]
@ant31 , @michelleN , can you help to review and approve it ? I need lgtm and approved labels for this PR. Thanks.

**Comment by zheddie** [comment]
Looks like this PR is still need a "approved" label. Not know who could do help ? @ant31  @michelleN  , can you help to review and approve it ? thanks.

**Pull request merged**
