### PR TITLE
Update to Kubernetes v1.18.2

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
@nan-yu, can you please help me fix these test failures. We would like to see client-go updated to v1.18.x .

**Comment by nan-yu** [comment]
> Nan Yu, can you please help me fix these test failures. We would like to see client-go updated to v1.18.x .

There're a couple of issues need to be fixed. I addressed them in my fork: https://github.com/nan-yu/application/commit/fb9cca9591b38f83e6fab8b960dc734c911147d8. Please take a look.

Here is the summary:
- merge `app.k8s.io_applications.yaml` with `app.k8s.io_applications.v1.yaml` to get rid of the `v1beta1` version of CRD
- replace the deprecated `apiextensions.k8s.io/v1beta1` version with `apiextensions.k8s.io/v1beta1`
- add `kubectl` to the PATH as the latest controller-gen depends on `kubectl`
- remove `kind get kubeconfig-path --name="kind"` as `kubeconfig-path` was depracated in kind v0.8.1
- delete an empty file
- update `customerreource.go` to use the v1 API instead of v1beta1 add license to the generated resources
- remove the extra `type` field from the test `application.yaml` file
- add the `version` field to the test GVK

And a successful travis build: https://travis-ci.com/github/nan-yu/application/builds/189108875

**Comment by tamalsaha** [comment]
Thanks @nan-yu ! If you want to open a pr, you are most welcome. I can close this one in that case.

**Comment by nan-yu** [comment]
> Thanks Nan Yu ! If you want to open a pr, you are most welcome. I can close this one in that case.

Sure. The fixes, along with your original changes, are in https://github.com/kubernetes-sigs/application/pull/207.
Thanks again for the update!

**Pull request closed without merging**
