### PR TITLE
Fix directory name following a rename

### PR DESCRIPTION
**Pull request by martinmaly**
The recent rename of a binary accidentally renamed a directory path also.

### CODE REVIEW

**Comment by barney-s** [comment]
@martinmaly  - thanks for this change.

@ant31 - Would you also please review this. Specifically the namespace changes.

**Comment by ant31** [comment]
should be fixed with #179 
I would not change the namespace

**Comment by barney-s** [comment]
@ant31 - with the latest changes would this be fixed ?

**Comment by martinmaly** [comment]
obsolete

**Pull request closed without merging**
