### PR TITLE
Add Travis Build file to run the unit tests

### PR DESCRIPTION
**Pull request by nan-yu**

### CODE REVIEW

**Comment by nan-yu** [comment]
@barney-s 
This PR is ready to be reviewed and merged. Travis build completed successfully on my fork PR: https://github.com/nan-yu/application/pull/1
image

Currently, Travis is configured to only run unit tests. I'll add e2e test in a separate PR later.
Once the PR is merged, Travis build should be triggered when new PRs are created.

**Comment by mortent** [comment]
This mostly looks good to me. Only question is how the Travis build will work with tide? Presumably we want a passing to be required before merge.

**Comment by nan-yu** [comment]
> Only question is how the Travis build will work with tide? Presumably we want a passing to be required before merge.

I thought they would not interfere with each other. When this PR is merged, there will be an extra Travis check added. If the Travis check fails, it won't allow the PR to be merged even if tide check passes.

**Comment by janetkuo** [comment]
/approve 

Thanks @nan-yu!

**Pull request merged**
