### PR TITLE
Add ant31 to the approvers list

### PR DESCRIPTION
**Pull request by ant31**
Adding myself to as an approver to help reviewing issues and PR. 

I'll update progress on sig-apps and ping others maintainers when needed before approving a PR.

### CODE REVIEW

**Comment by prydonius** [comment]
I'm okay with this given your previous involvement in this.

cc @kow3ns @mattfarina @janetkuo

**Comment by ant31** [comment]
@barney-s could you /lgtm again ? :)

**Comment by janetkuo** [comment]
/approve

Thanks @ant31!

**Pull request merged**
