### PR TITLE
Move from gopkg to gomod and newer dependencies

### PR DESCRIPTION
**Pull request by barney-s**
1. Move from gopkg to gomod
2. Remove vendor folder
3. Pull in newer controller-gen tooling

### CODE REVIEW

**Comment by mortent** [comment]
Can we remove the two commits that touch the OWNERS files from the PR? Also, the title of the PR needs to be changed before we merge.

Have we verified that the generated Application CRD definition remains unchanged after this PR?

**Comment by barney-s** [comment]
@mortent  
There is no change in CRD

Also removed the commits touching OWNERS file.

**Comment by mortent** [comment]
/lgtm
We also need to remove WIP from the title before we merge. Not sure why the invalid-owners-file label is still set.

**Comment by barney-s** [comment]
@janetkuo @kow3ns  - would you please approve this ?

**Comment by barney-s** [comment]
@mortent do you mind LGTM'ing again

**Comment by mortent** [comment]
Why did we merge master into this branch? And it looks like this will remove you from the reviewers and approvers lists. Didn't you just update them?

**Comment by barney-s** [comment]
> Why did we merge master into this branch? And it looks like this will remove you from the reviewers and approvers lists. Didn't you just update them?

There was a merge conflict post travis/e2e test merges.
Will fix the owners file.

**Pull request merged**
